image: node:14.16.0

definitions: 
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm test
        # script:
        #   - npm install eslint
        #   - npx eslint .

pipelines:

  branches:
    feature/*:
      - step: *build-test
      - step:
          name: Build Docker
          services:
            - docker
          caches:
            - docker
          script:
            - docker build -t sputnik-v1-api -t sputnik-v1-api:${BITBUCKET_TAG} .

      - step:
          name: Publish Docker
          services:
            - docker
          caches:
            - docker
          script: 
            - pipe: atlassian/aws-ecr-push-image:1.2.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: sputnik-v1-api
                TAGS: '${BITBUCKET_TAG} latest'

      - step:
          name: Deploy Helm
          script:
            - pipe: docker://myspace/bitbucket-k8-helm-pipe:latest
              variables:
                BUILD_HELM: 'yes'
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_REGION: $AWS_DEFAULT_REGION
                EKS_CLUSTER: sputnik-eks
                VERSION: $BITBUCKET_BUILD_NUMBER
                PROJECT: sputnik-v1-api
                NAMESPACE: sputnik
