image: node:14.16.0

definitions:
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm test
        # script:
        #   - npm install eslint
        #   - npx eslint .

pipelines:

  branches:
    feature/*:
      # - step: *build-test

      # - step:
      #     name: Docker - Build and Publish
      #     services:
      #       - docker
      #     caches:
      #       - docker
      #     script:
      #       - >-
      #         docker build 
      #         -t $APP_NAME:latest
      #         -t $APP_NAME:develop-latest
      #         -t $APP_NAME:develop-$BITBUCKET_COMMIT
      #         .
      #       - pipe: atlassian/aws-ecr-push-image:1.4.2
      #         variables:
      #           AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      #           AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      #           AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      #           IMAGE_NAME: $APP_NAME
      #           TAGS: >-
      #             latest
      #             develop-latest
      #             develop-$BITBUCKET_COMMIT

      - step:
          name: Helm - Build and Deploy
          image: alpine/helm:3.6.3          
          script:
            - export CHART_FOLDER=deployment/app-chart
            - helm lint $CHART_FOLDER
            - >-
              helm template $APP_NAME $CHART_FOLDER 
              --set image.tag=develop-$BITBUCKET_COMMIT
              > $APP_NAME-manifest.yml

            - pipe: atlassian/aws-eks-kubectl-run:1.4.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                CLUSTER_NAME: $EKS_CLUSTER_NAME
                KUBECTL_COMMAND: 'apply'
                RESOURCE_PATH: '$APP_NAME-manifest.yml'
                DEBUG: 'true'
                KUBECTL_ARGS:
                  - "-n $DEPLOYMENT_NAMESPACE"
