image: node:14.16.0

definitions: 
  steps:
    - step: &build-test
        name: Build and test
        caches:
          - node
        script:
          - npm install
          - npm test
        script:
          - npm install eslint
          - npx eslint .

pipelines:

  branches:
    feature/*:
      - step: *build-test
      - step:
          name: Build Docker
          services:
            - docker
          caches:
            - docker
          script:
            - docker build -t sputnik-v1-api .

      - step:
          name: Publish Docker
          services:
            - docker
          caches:
            - docker
          script: 
            - pipe: atlassian/aws-ecr-push-image:1.2.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: sputnik-v1-api
                TAGS: '${BITBUCKET_TAG} latest'
