version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5437:5432'
    volumes:
      - pg-data:/data/postgres
    env_file:
      - .env.docker-dev
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pg-data:/root/.pgadmin
    env_file:
      - .env.docker-dev
    networks:
      - postgres

  redis:
    image: 'redis:alpine'
    env_file:
      - .env.docker-dev
    ports:
      - '6379:6379'
    networks:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - redis

  rabbitmq:
    image: bitnami/rabbitmq:3.9
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/bitnami
    networks:
      - rabbitmq

volumes:
  pg-data:
  rabbitmq-data:

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
  rabbitmq:
    driver: bridge
