test:
  env: ${TEST_ENV:dev}
  accountId: testdao2.testnet
#  accountId: automation-01.testnet
  dao: test-dao-1641395769436.sputnikv2.testnet
  aggregation.timeout: ${TEST_AGG_TIMEOUT:20}

framework:
  http.timeout: 20

accounts:
  account1:
    accountId: testdao2.testnet
    publicKey: ed25519:8kqG6dyAheDqzoZh4hk9HbjBngG6fTnCD4zTw6sVud9K
    signature: JJoq7fvBh6JXH9kVXtV0SoeT3YDSm9Gr6Ug4cmJNXAtuU2bZFu9/8bN26xw7MwYBRdWTZr2v81JZDO9zYaE8Dg==