name: 'Helm Deploy'
runs:
  using: 'docker'
  image: 'alpine/helm:3.6.3'
  steps:
  - run: |
      export CHART_FOLDER=apps/${SUBAPP_NAME}/deployment/app-chart
      helm lint $CHART_FOLDER
  - name: helm deploy
    uses: koslib/helm-eks-action@v1.8.0
    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    with:
      command: |
        helm template $APP_NAME-$SUBAPP_NAME $CHART_FOLDER \
          --set image.tag=$DOCKER_ENV_TAG \
          --set environment.near_env=${secrets.NEAR_ENV} \
          --set environment.near_contract_name=${secrets.NEAR_CONTRACT_NAME} \
          --set environment.near_token_factory_contract_name=${secrets.NEAR_TOKEN_FACTORY_CONTRACT_NAME} \
          --set environment.near_bridge_token_factory_contract_name=${secrets.NEAR_BRIDGE_TOKEN_FACTORY_CONTRACT_NAME} \
          --set environment.wallet_callback_url=${secrets.WALLET_CALLBACK_URL} \
          --set ingress.host=${secrets.K8S_INGRESS_HOST}

