apiVersion: v1
kind: Service
metadata:
  name: {{ include "sputnik-v1-api.fullname" . }}
  labels:
    {{- include "sputnik-v1-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      
  selector:
    {{- include "sputnik-v1-api.selectorLabels" . | nindent 4 }}
