name: 'Docker Build Publish'
runs:
  steps:
  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: |
        ${secrets.AWS_ECR_URL}-${SUBAPP_NAME}
      tags: |
        type=raw,value=latest
        type=ref,event=branch,suffix=-latest
        type=sha

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

  - name: Login to ECR
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build And Push
    uses: docker/build-push-action@v2
    with:
      #context: apps/${SUBAPP_NAME}
      context: .
      #file: apps/${SUBAPP_NAME}/Dockerfile
      file: Dockerfile
      platforms: linux/amd64
      tags: ${{ steps.meta.outputs.tags }}
      push: true
