name: Build Deploy Aggregator
on:
  workflow_dispatch:
  push:
    branches:
    - develop
    - staging
    paths:
    - 'apps/aggregator/**'
    - 'libs/**'

jobs:
  build-deploy:
    name: Build Deploy
    environment:
      name: ${GITHUB_REF##*/}
      url: https://${K8S_INGRESS_HOST}
    steps:
    - name: Set Environment
      run: |
         echo DOCKER_ENV_TAG=${GITHUB_REF##*/}-$GITHUB_SHA >> $GITHUB_ENV
         echo SUBAPP_NAME=aggregator >> $GITHUB_ENV

    - name: Build Test
      uses: ./.github/actions/build-test

    - name: Docker Build Publish
      uses: ./.github/actions/docker-build-publish

    - name: Helm Deploy
      uses: ./.github/actions/helm-build-deploy
