apiVersion: v1
kind: ConfigMap
metadata:
  name: sputnik-v2-notifier-configmap
data:
  NODE_OPTIONS: ' --max-old-space-size={{ include "node.maxOldSpaceSize" . }} '
  PORT: "3000"
  NEST_APP_TYPE: notifier
  NOTIFI_ENV: "{{ .Values.environment.notifi_env }}"
